### ISSUE TITLE
grlib_tester / logic_top 

### ISSUE THREAD

**Issue by bklolo** [UHCL-CENG-SeniorProject-2021/FPGA#6]
`grlib_tester` is `logic_top` with a different name.

A rename/replacement can be pushed to `master` branch.

**Comment by UHCL-CENG-SeniorProject-2021** [comment]
Deleted grlib_tester [9a5d006](https://github.com/UHCL-CENG-SeniorProject-2021/FPGA/commit/9a5d006daf5b1aed1a3c1b9629f53dc2126aff34#diff-5f2b00fc1dbbaa1f86ea651b746c618ef4d8915cf66aa61026839980b6d6a1c2)
Edited logic_top to reflect deletion [a858d8a](https://github.com/UHCL-CENG-SeniorProject-2021/FPGA/commit/a858d8ac85d6385477498760adc53b89aa89c59c#diff-5f2b00fc1dbbaa1f86ea651b746c618ef4d8915cf66aa61026839980b6d6a1c2)

**Comment by bklolo** [comment]
closing issue
